-- seed.sql — full seed: categories, brands, spec definitions, 65 products with
-- bilingual descriptions + search keywords, featured flags, site content.
--
-- Notes
--  * All 65 products are seeded as PUBLISHED (is_published = true).
--  * Descriptions = usage line + technical line, taken from the owner's product
--    spec sheet (usage + specs per product). Filterable numbers (zones, loops,
--    voltage, capacity, weight, material) are also stored in the specs column.
--  * Availability: "غير متوفر قريباً = on_request, متوفر لفترة محدودة = limited, else in_stock".
--  * Panels named "لوحة اطفاء" (HST / Convoy / Apollo) are automatic-extinguishing control panels.
--  * Re-runnable: rows that already exist are kept; only EMPTY description /
--    search_keywords fields are filled (admin edits are never overwritten).
--  * To start completely clean first, run the RESET block below (destructive).
--  * Phone numbers are placeholders; verified social profiles are not seeded.

-- ── RESET (optional, destructive — uncomment only for a full wipe) ───────
-- truncate table
--   public.product_images, public.products, public.series, public.spec_definitions,
--   public.brands, public.categories, public.certificates, public.contact_numbers,
--   public.social_links, public.site_settings, public.projects
-- restart identity cascade;

-- ── Categories (17) ──────────────────────────────────────────────────────
insert into public.categories (slug, name_ar, name_en, sort_order) values
  ('control-panels',         'لوحات الإطفاء',                'Control Panels',         1),
  ('smoke-detectors',        'حساسات الدخان',                 'Smoke Detectors',        2),
  ('heat-detectors',         'حساسات الحرارة',                'Heat Detectors',         3),
  ('multi-sensor-detectors', 'حساسات متعددة',                  'Multi-Sensor Detectors', 4),
  ('manual-call-points',     'كاسر زجاج يدوي',                'Manual Call Points',     5),
  ('sirens',                 'السيرينات',                     'Sirens',                 6),
  ('bells',                  'أجراس الإنذار',                 'Bells',                  7),
  ('remote-indicators',      'لمبات البيان',                  'Remote Indicators',      8),
  ('flame-detectors',        'حساسات اللهب',                  'Flame Detectors',        9),
  ('gas-detectors',          'حساسات الغاز',                  'Gas Detectors',         10),
  ('beam-detectors',         'البيم',                         'Beam Detectors',        11),
  ('detector-bases',         'قواعد الحساسات',                'Detector Bases',        12),
  ('cables',                 'الكابلات',                      'Cables',                13),
  ('batteries',              'البطاريات',                     'Batteries',             14),
  ('extinguishers',          'طفايات الحريق',                 'Extinguishers',         15),
  ('modules',                'وحدات (مونتور / كنترول / انترفيس)', 'Modules',          16),
  ('abort-switches',         'أزرار الإلغاء',                 'Abort Switches',        17)
on conflict (slug) do nothing;

-- ── Brands (7) ───────────────────────────────────────────────────────────
insert into public.brands (slug, name_ar, name_en, sort_order) values
  ('hst',             'HST',             'HST',               1),
  ('convoy',          'كونفوي',          'Convoy',            2),
  ('snower',          'اسنوير',          'Snower',            3),
  ('tanda',           'تاندا',           'Tanda',             4),
  ('ats',             'ATS',             'ATS',               5),
  ('apollo',          'ابولو',           'Apollo',             6),
  ('hlt',             'HLT',             'HLT',                7)
on conflict (slug) do nothing;

-- ── Spec definitions (form fields + filter labels per category) ──────────
insert into public.spec_definitions (category_id, key, label_ar, label_en, unit, value_type, options, is_filterable, sort_order)
select c.id, v.key, v.label_ar, v.label_en, v.unit, v.value_type, v.options::jsonb, v.is_filterable, v.sort_order
from (values
  ('control-panels', 'zones',       'عدد الزونات',        'Zones',             null, 'number', null::text,  true,  1),
  ('control-panels', 'loops',       'عدد اللوبات',        'Loops',             null, 'number', null,       true,  2),
  ('sirens',         'voltage',     'الفولت',             'Voltage',           'V',  'number', null,       true,  1),
  ('bells',          'voltage',     'الفولت',             'Voltage',           'V',  'number', null,       true,  1),
  ('batteries',      'capacity_ah', 'السعة',              'Capacity',          'Ah', 'number', null,       true,  1),
  ('extinguishers',  'weight_kg',   'الوزن',              'Weight',            'kg', 'number', null,       true,  1),
  ('batteries',      'voltage',     'الفولت',             'Voltage',           'V',  'number', null,       false, 2),
  ('cables',         'material',    'المادة',             'Material',          null, 'select',
       '[{"value":"copper","label_ar":"نحاس","label_en":"Copper"},{"value":"aluminum","label_ar":"ألومنيوم","label_en":"Aluminum"}]', true, 1)
) as v(category, key, label_ar, label_en, unit, value_type, options, is_filterable, sort_order)
join public.categories c on c.slug = v.category
on conflict (category_id, key) do nothing;

-- ── Products (65) — published, with descriptions ─────────────────────────
-- Panels with zones are marked conventional, panels with loops addressable.
with s(slug, category, brand, system, name_ar, name_en, description_ar, description_en, search_keywords, specs, availability, sort_order) as (values
  ('hst-extinguishing-panel', 'control-panels', 'hst', null, 'لوحة اطفاء hst', 'HST Extinguishing Panel',
   'لوحة تحكم متخصصة لإدارة أنظمة الإطفاء التلقائي بالغاز. مخرجات لتفعيل أسطوانات الغاز (Solenoid)، ودوائر تقاطع مناطق الإنذار (Cross-zoning)، ومؤقت تأخير التفريغ.',
   'Control panel specialized in managing automatic gas extinguishing systems. Outputs for activating gas cylinders (solenoid), alarm zone cross-zoning circuits, and a discharge delay timer.',
   'لوحة اطفاء hst HST Extinguishing Panel اتش اس تي hst لوحة لوحات كنترول بانل panel control panel',
   '{}'::jsonb, 'in_stock', 1),
  ('hst-2-zone-panel', 'control-panels', 'hst', null, 'لوحة 2 زون hst', 'HST 2-Zone Panel',
   'لوحة إنذار حريق تقليدية (Conventional) للمساحات الصغيرة والمتوسطة. تغطي منطقتين مستقلتين، تدعم حتى 20–30 كاشف لكل زون، جهد تشغيل 24V DC.',
   'Conventional fire alarm panel for small and medium spaces. Covers two independent zones, supports up to 20–30 detectors per zone, 24V DC operating voltage.',
   'لوحة 2 زون hst HST 2-Zone Panel اتش اس تي hst لوحة لوحات كنترول بانل panel control panel زون zone conventional',
   '{"zones":2}', 'in_stock', 2),
  ('hst-economy-4-zone-panel', 'control-panels', 'hst', null, 'لوحة 4 زون الاقتصادية hst', 'HST Economy 4-Zone Panel',
   'لوحة إنذار تقليدية اقتصادية 4 زون لتغطية المباني والمحلات التجارية. 4 زون، مؤشرات LED لكل منطقة، ومخرجات ريلاي للأعطال والسرينات.',
   'Economy 4-zone conventional alarm panel for buildings and retail shops. 4 zones, an LED indicator per zone, and relay outputs for faults and sirens.',
   'لوحة 4 زون الاقتصادية hst HST Economy 4-Zone Panel اتش اس تي hst لوحة لوحات كنترول بانل panel control panel زون zone conventional',
   '{"zones":4}', 'in_stock', 3),
  ('hst-economy-8-zone-panel', 'control-panels', 'hst', null, 'لوحة 8 زون الاقتصادية hst', 'HST Economy 8-Zone Panel',
   'لوحة إنذار تقليدية اقتصادية 8 زون لتغطية المباني والمحلات التجارية. 8 زون، مؤشرات LED لكل منطقة، ومخرجات ريلاي للأعطال والسرينات.',
   'Economy 8-zone conventional alarm panel for buildings and retail shops. 8 zones, an LED indicator per zone, and relay outputs for faults and sirens.',
   'لوحة 8 زون الاقتصادية hst HST Economy 8-Zone Panel اتش اس تي hst لوحة لوحات كنترول بانل panel control panel زون zone conventional',
   '{"zones":8}', 'on_request', 4),
  ('hst-economy-12-zone-panel', 'control-panels', 'hst', null, 'لوحة 12 زون الاقتصادية hst', 'HST Economy 12-Zone Panel',
   'لوحة إنذار تقليدية اقتصادية 12 زون لتغطية المباني والمحلات التجارية. 12 زون، مؤشرات LED لكل منطقة، ومخرجات ريلاي للأعطال والسرينات.',
   'Economy 12-zone conventional alarm panel for buildings and retail shops. 12 zones, an LED indicator per zone, and relay outputs for faults and sirens.',
   'لوحة 12 زون الاقتصادية hst HST Economy 12-Zone Panel اتش اس تي hst لوحة لوحات كنترول بانل panel control panel زون zone conventional',
   '{"zones":12}', 'on_request', 5),
  ('hst-economy-16-zone-panel', 'control-panels', 'hst', null, 'لوحة 16 زون الاقتصادية hst', 'HST Economy 16-Zone Panel',
   'لوحة إنذار تقليدية اقتصادية 16 زون لتغطية المباني والمحلات التجارية. 16 زون، مؤشرات LED لكل منطقة، ومخرجات ريلاي للأعطال والسرينات.',
   'Economy 16-zone conventional alarm panel for buildings and retail shops. 16 zones, an LED indicator per zone, and relay outputs for faults and sirens.',
   'لوحة 16 زون الاقتصادية hst HST Economy 16-Zone Panel اتش اس تي hst لوحة لوحات كنترول بانل panel control panel زون zone conventional',
   '{"zones":16}', 'limited', 6),
  ('hst-silver-4-zone-panel', 'control-panels', 'hst', null, 'لوحة 4 زون السيلفر hst', 'HST Silver 4-Zone Panel',
   'لوحة إنذار تقليدية 4 زون من الفئة المتقدمة، بهيكل معزز وحماية أعلى. سرعة معالجة أسرع للدوائر الكهربائية، حماية ضد قفزات التيار، وواجهة تحكم متطورة.',
   'Advanced-class conventional alarm panel with 4 zones, a reinforced enclosure and higher protection. Faster circuit processing, surge protection, and an advanced control interface.',
   'لوحة 4 زون السيلفر hst HST Silver 4-Zone Panel اتش اس تي hst لوحة لوحات كنترول بانل panel control panel زون zone conventional',
   '{"zones":4}', 'limited', 7),
  ('hst-silver-8-zone-panel', 'control-panels', 'hst', null, 'لوحة 8 زون السيلفر hst', 'HST Silver 8-Zone Panel',
   'لوحة إنذار تقليدية 8 زون من الفئة المتقدمة، بهيكل معزز وحماية أعلى. سرعة معالجة أسرع للدوائر الكهربائية، حماية ضد قفزات التيار، وواجهة تحكم متطورة.',
   'Advanced-class conventional alarm panel with 8 zones, a reinforced enclosure and higher protection. Faster circuit processing, surge protection, and an advanced control interface.',
   'لوحة 8 زون السيلفر hst HST Silver 8-Zone Panel اتش اس تي hst لوحة لوحات كنترول بانل panel control panel زون zone conventional',
   '{"zones":8}', 'limited', 8),
  ('hst-silver-16-zone-panel', 'control-panels', 'hst', null, 'لوحة 16 زون السيلفر hst', 'HST Silver 16-Zone Panel',
   'لوحة إنذار تقليدية 16 زون من الفئة المتقدمة، بهيكل معزز وحماية أعلى. سرعة معالجة أسرع للدوائر الكهربائية، حماية ضد قفزات التيار، وواجهة تحكم متطورة.',
   'Advanced-class conventional alarm panel with 16 zones, a reinforced enclosure and higher protection. Faster circuit processing, surge protection, and an advanced control interface.',
   'لوحة 16 زون السيلفر hst HST Silver 16-Zone Panel اتش اس تي hst لوحة لوحات كنترول بانل panel control panel زون zone conventional',
   '{"zones":16}', 'limited', 9),
  ('hst-mcp', 'manual-call-points', 'hst', null, 'كاسر hst', 'HST Manual Call Point',
   'نقطة استدعاء يدوية (Manual Call Point) لتفعيل الإنذار يدويًا. إمكانية إعادة الضبط بمفتاح خاص دون الحاجة لكسر الزجاج.',
   'Manual call point for triggering the alarm by hand. Can be reset with a special key without breaking the glass.',
   'كاسر hst HST Manual Call Point اتش اس تي hst كاسر كسر زجاج manual call point break glass',
   '{}', 'in_stock', 10),
  ('hst-siren', 'sirens', 'hst', null, 'سرينة hst', 'HST Siren',
   'سرينة إنذار صوتية لإخلاء المبنى. شدة صوت عالية (90–105 ديسيبل)، تعمل على جهد 24V DC.',
   'Audible alarm siren for evacuating the building. High sound level (90–105 dB), operates at 24V DC.',
   'سرينة hst HST Siren اتش اس تي hst سرينة سيرينة صفارة siren',
   '{"voltage":24}', 'in_stock', 11),
  ('hst-bell', 'bells', 'hst', null, 'جرس hst', 'HST Bell',
   'جرس إنذار صوتي لإخلاء المبنى. شدة صوت عالية (90–105 ديسيبل)، تعمل على جهد 24V DC.',
   'Audible alarm bell for evacuating the building. High sound level (90–105 dB), operates at 24V DC.',
   'جرس hst HST Bell اتش اس تي hst جرس اجراس bell',
   '{"voltage":24}', 'in_stock', 12),
  ('hst-conventional-smoke-detector', 'smoke-detectors', 'hst', 'conventional', 'حساس دخان تقليدي hst', 'HST Conventional Smoke Detector',
   'كاشف دخان ضوئي (Photoelectric) للاستشعار المبكر للحرائق ذات الدخان الظاهر. جهد تشغيل 12–24V DC، غطاء معزز ضد الأتربة والحشرات، مخرج للمبة بيان خارجية.',
   'Photoelectric smoke detector for early sensing of fires that produce visible smoke. 12–24V DC operating voltage, reinforced cover against dust and insects, output for an external indicator lamp.',
   'حساس دخان تقليدي hst HST Conventional Smoke Detector اتش اس تي hst حساس دخان كاشف smoke detector تقليدي conventional',
   '{}', 'in_stock', 13),
  ('hst-conventional-heat-detector', 'heat-detectors', 'hst', 'conventional', 'حساس حرارة تقليدي hst', 'HST Conventional Heat Detector',
   'كاشف حراري يستشعر الارتفاع المفاجئ في درجات الحرارة. تشغيل عند 57°م أو بمعدل ارتفاع الحرارة (Rate of Rise)، مناسب للمطابخ والأماكن المتربة.',
   'Heat detector that senses sudden temperature rises. Triggers at 57°C or by rate of rise, suitable for kitchens and dusty areas.',
   'حساس حرارة تقليدي hst HST Conventional Heat Detector اتش اس تي hst حساس حرارة كاشف heat detector تقليدي conventional',
   '{}', 'in_stock', 14),
  ('hst-conventional-multi-sensor-detector', 'multi-sensor-detectors', 'hst', 'conventional', 'حساس متعدد تقليدي hst', 'HST Conventional Multi-Sensor Detector',
   'كاشف مدمج يعمل بالتقنية الضوئية والحرارية معًا. يقلل الإنذارات الكاذبة من خلال الدمج الخوارزمي بين استشعار الحرارة والدخان.',
   'Combined detector using photoelectric and heat technology together. Reduces false alarms through algorithmic fusion of heat and smoke sensing.',
   'حساس متعدد تقليدي hst HST Conventional Multi-Sensor Detector اتش اس تي hst حساس متعدد دخان وحرارة multi sensor detector تقليدي conventional',
   '{}', 'in_stock', 15),
  ('hst-remote-indicator', 'remote-indicators', 'hst', null, 'لمبة بيان hst', 'HST Remote Indicator',
   'مؤشر إضاءة أحمر خارجي يوضع على أبواب الغرف المغلقة. إضاءة LED عالية السطوع مع استهلاك منخفض جدًا للتيار للتدليل على الكاشف المفعّل.',
   'External red indicator lamp placed on the doors of closed rooms. High-brightness LED with very low current consumption to indicate the activated detector.',
   'لمبة بيان hst HST Remote Indicator اتش اس تي hst لمبة بيان remote indicator',
   '{}', 'in_stock', 16),
  ('hst-flame-detector', 'flame-detectors', 'hst', null, 'حساس لهب hst', 'HST Flame Detector',
   'كاشف يستشعر الإشعاعات الضوئية (UV/IR) الصادرة عن اللهب المباشر. استجابة فائقة السرعة للحرائق اللحظية، مناسب للمخازن ومستودعات الوقود والمناطق المفتوحة.',
   'Detector that senses the optical radiation (UV/IR) emitted by direct flames. Very fast response to instantaneous fires, suitable for warehouses, fuel depots and open areas.',
   'حساس لهب hst HST Flame Detector اتش اس تي hst حساس لهب flame detector',
   '{}', 'in_stock', 17),
  ('hst-conventional-gas-detector', 'gas-detectors', 'hst', 'conventional', 'حساس غاز تقليدي hst', 'HST Conventional Gas Detector',
   'كاشف لتسرب الغازات البترولية المسالة (LPG) أو غاز الميثان. سرينة مدمجة ومخرج ريلاي لإغلاق محابس الغاز تلقائيًا عند التسرب.',
   'Detector for liquefied petroleum gas (LPG) or methane leaks. Built-in siren and a relay output to automatically close gas valves on a leak.',
   'حساس غاز تقليدي hst HST Conventional Gas Detector اتش اس تي hst حساس غاز gas detector تقليدي conventional',
   '{}', 'in_stock', 18),
  ('hst-beam-detector', 'beam-detectors', 'hst', null, 'بيم hst', 'HST Beam Detector',
   'كاشف دخان شعاعي (Beam Detector) للمساحات الشاسعة والارتفاعات العالية. يتكون من مرسل وعاكس/مستقبل لتغطية مسافات من 8 إلى 100 متر.',
   'Beam smoke detector for vast spaces and high ceilings. Consists of a transmitter and a reflector/receiver, covering distances from 8 to 100 m.',
   'بيم hst HST Beam Detector اتش اس تي hst بيم beam detector حساس شعاعي',
   '{}', 'limited', 19),
  ('hst-economy-1-loop-panel', 'control-panels', 'hst', null, 'لوحة 1loop الاقتصادية hst', 'HST Economy 1-Loop Panel',
   'لوحة معنونة (Addressable) لوب واحد لتحديد موضع الحريق بدقة على مستوى الكاشف. سعة تصل إلى 127 أداة، وشاشة LCD لإظهار اسم وتفاصيل المنطقة.',
   'Addressable 1-loop panel that pinpoints the fire location down to the individual detector. Capacity up to 127 devices, with an LCD showing the zone name and details.',
   'لوحة 1loop الاقتصادية hst HST Economy 1-Loop Panel اتش اس تي hst لوحة لوحات كنترول بانل panel control panel لوب loop addressable معنونة',
   '{"loops":1}', 'limited', 20),
  ('hst-economy-2-loop-panel', 'control-panels', 'hst', null, 'لوحة 2loop الاقتصادية hst', 'HST Economy 2-Loop Panel',
   'لوحة معنونة (Addressable) لوبان لتحديد موضع الحريق بدقة على مستوى الكاشف. سعة تصل إلى 254 أداة (127 لكل لوب)، وشاشة LCD لإظهار اسم وتفاصيل المنطقة.',
   'Addressable 2-loop panel that pinpoints the fire location down to the individual detector. Capacity up to 254 devices (127 per loop), with an LCD showing the zone name and details.',
   'لوحة 2loop الاقتصادية hst HST Economy 2-Loop Panel اتش اس تي hst لوحة لوحات كنترول بانل panel control panel لوب loop addressable معنونة',
   '{"loops":2}', 'on_request', 21),
  ('hst-red-2-loop-panel', 'control-panels', 'hst', null, 'لوحة 2loop الحمرة hst', 'HST Red 2-Loop Panel',
   'لوحة معنونة احترافية 2 لوب، مخصصة للمنشآت والمباني الكبيرة. الفئة تدعم من 2 إلى 4 حلقات معنونة، وسعة تصل إلى 1000 نقطة، وإمكانية الربط الشبكي (Networking)، وبرمجة سيناريوهات الإخلاء.',
   'Professional addressable 2-loop panel for large facilities and buildings. The series supports 2 to 4 addressable loops, capacity up to 1000 points, networking, and programmable evacuation scenarios.',
   'لوحة 2loop الحمرة hst HST Red 2-Loop Panel اتش اس تي hst لوحة لوحات كنترول بانل panel control panel لوب loop addressable معنونة',
   '{"loops":2}', 'limited', 22),
  ('hst-red-4-loop-panel', 'control-panels', 'hst', null, 'لوحة 4loop الحمرة hst', 'HST Red 4-Loop Panel',
   'لوحة معنونة احترافية 4 لوب، مخصصة للمنشآت والمباني الكبيرة. الفئة تدعم من 2 إلى 4 حلقات معنونة، وسعة تصل إلى 1000 نقطة، وإمكانية الربط الشبكي (Networking)، وبرمجة سيناريوهات الإخلاء.',
   'Professional addressable 4-loop panel for large facilities and buildings. The series supports 2 to 4 addressable loops, capacity up to 1000 points, networking, and programmable evacuation scenarios.',
   'لوحة 4loop الحمرة hst HST Red 4-Loop Panel اتش اس تي hst لوحة لوحات كنترول بانل panel control panel لوب loop addressable معنونة',
   '{"loops":4}', 'on_request', 23),
  ('hst-addressable-mcp', 'manual-call-points', 'hst', 'addressable', 'كاسر معنون hst', 'HST Addressable Manual Call Point',
   'نقطة استدعاء يدوية (Manual Call Point) لتفعيل الإنذار يدويًا. له عنوان خاص على اللوب. إمكانية إعادة الضبط بمفتاح خاص دون الحاجة لكسر الزجاج.',
   'Manual call point for triggering the alarm by hand. Has its own address on the loop. Can be reset with a special key without breaking the glass.',
   'كاسر معنون hst HST Addressable Manual Call Point اتش اس تي hst كاسر كسر زجاج manual call point break glass معنون addressable',
   '{}', 'in_stock', 24),
  ('hst-addressable-smoke-detector', 'smoke-detectors', 'hst', 'addressable', 'حساس دخان معنون hst', 'HST Addressable Smoke Detector',
   'كاشف دخان ضوئي (Photoelectric) للاستشعار المبكر للحرائق ذات الدخان الظاهر. غطاء معزز ضد الأتربة والحشرات، ومخرج للمبة بيان خارجية. له عنوان خاص على اللوب.',
   'Photoelectric smoke detector for early sensing of fires that produce visible smoke. Reinforced cover against dust and insects, with an output for an external indicator lamp. Has its own address on the loop.',
   'حساس دخان معنون hst HST Addressable Smoke Detector اتش اس تي hst حساس دخان كاشف smoke detector معنون addressable',
   '{}', 'in_stock', 25),
  ('hst-addressable-heat-detector', 'heat-detectors', 'hst', 'addressable', 'حساس حرارة معنون hst', 'HST Addressable Heat Detector',
   'كاشف حراري يستشعر الارتفاع المفاجئ في درجات الحرارة. تشغيل عند 57°م أو بمعدل ارتفاع الحرارة (Rate of Rise)، مناسب للمطابخ والأماكن المتربة. له عنوان خاص على اللوب.',
   'Heat detector that senses sudden temperature rises. Triggers at 57°C or by rate of rise, suitable for kitchens and dusty areas. Has its own address on the loop.',
   'حساس حرارة معنون hst HST Addressable Heat Detector اتش اس تي hst حساس حرارة كاشف heat detector معنون addressable',
   '{}', 'in_stock', 26),
  ('hst-addressable-multi-sensor-detector', 'multi-sensor-detectors', 'hst', 'addressable', 'حساس متعدد معنون hst', 'HST Addressable Multi-Sensor Detector',
   'كاشف مدمج يعمل بالتقنية الضوئية والحرارية معًا. يقلل الإنذارات الكاذبة من خلال الدمج الخوارزمي بين استشعار الحرارة والدخان. له عنوان خاص على اللوب.',
   'Combined detector using photoelectric and heat technology together. Reduces false alarms through algorithmic fusion of heat and smoke sensing. Has its own address on the loop.',
   'حساس متعدد معنون hst HST Addressable Multi-Sensor Detector اتش اس تي hst حساس متعدد دخان وحرارة multi sensor detector معنون addressable',
   '{}', 'in_stock', 27),
  ('hst-monitor-module', 'modules', 'hst', 'addressable', 'مونتور hst', 'HST Monitor Module',
   'وحدة معنونة لمراقبة الدخل. مراقبة مفاتيح تدفق المياه وإرسال حالتها إلى اللوحة.',
   'Addressable module for input monitoring. Monitors water flow switches and reports their state to the panel.',
   'مونتور hst HST Monitor Module اتش اس تي hst مونتور كنترول انترفيس module معنون addressable',
   '{}', 'in_stock', 28),
  ('hst-control-module', 'modules', 'hst', 'addressable', 'كنترول hst', 'HST Control Module',
   'وحدة معنونة للتحكم بالخرج. إرسال إشارات لإغلاق أبواب الحريق وإيقاف التكييف.',
   'Addressable module for output control. Sends signals to close fire doors and shut down air conditioning.',
   'كنترول hst HST Control Module اتش اس تي hst مونتور كنترول انترفيس module معنون addressable',
   '{}', 'limited', 29),
  ('hst-interface-module', 'modules', 'hst', 'addressable', 'انترفيس hst', 'HST Interface Module',
   'وحدة معنونة للتكامل مع الأنظمة والأجهزة الأخرى. موديول انترفيس يربط الأجهزة بنظام الإنذار المعنون.',
   'Addressable module for integration with other systems and devices. Interface module connecting devices to the addressable alarm system.',
   'انترفيس hst HST Interface Module اتش اس تي hst مونتور كنترول انترفيس module معنون addressable',
   '{}', 'limited', 30),
  ('convoy-extinguishing-panel', 'control-panels', 'convoy', null, 'لوحة اطفاء كونفوي', 'Convoy Extinguishing Control Panel',
   'لوحة تحكم لتفعيل أنظمة الإطفاء التلقائي. إدارة دوائر التفريغ والمراقبة الحثيثة.',
   'Control panel for activating automatic extinguishing systems. Manages discharge and close-monitoring circuits.',
   'لوحة اطفاء كونفوي Convoy Extinguishing Control Panel كونفوي convoy conway لوحة لوحات كنترول بانل panel control panel',
   '{}', 'limited', 31),
  ('hst-detector-base', 'detector-bases', 'hst', null, 'قاعدة hst', 'HST Detector Base',
   'قاعدة تثبيت بلاستيكية للحساسات والكواشف. توصيل مباشر لسلك شبكة الإنذار وتسهيل فك وتركيب الكاشف.',
   'Plastic mounting base for sensors and detectors. Direct connection of the alarm network wire and easy detector removal and installation.',
   'قاعدة hst HST Detector Base اتش اس تي hst قاعدة base detector base',
   '{}', 'in_stock', 32),
  ('snower-4-zone-panel', 'control-panels', 'snower', null, 'لوحة 4 زون اسنوير', 'Snower 4-Zone Panel',
   'لوحة إنذار تقليدية 4 زون عملية للمباني والمحلات التجارية. واجهة تشغيل مبسطة، مع دعم بطاريات طوارئ ومخرجات إنذار رئيسية.',
   'Practical 4-zone conventional alarm panel for buildings and retail shops. Simple operating interface with emergency battery support and main alarm outputs.',
   'لوحة 4 زون اسنوير Snower 4-Zone Panel اسنوير سنوير snower لوحة لوحات كنترول بانل panel control panel زون zone conventional',
   '{"zones":4}', 'in_stock', 33),
  ('snower-8-zone-panel', 'control-panels', 'snower', null, 'لوحة 8 زون اسنوير', 'Snower 8-Zone Panel',
   'لوحة إنذار تقليدية 8 زون عملية للمباني والمحلات التجارية. واجهة تشغيل مبسطة، مع دعم بطاريات طوارئ ومخرجات إنذار رئيسية.',
   'Practical 8-zone conventional alarm panel for buildings and retail shops. Simple operating interface with emergency battery support and main alarm outputs.',
   'لوحة 8 زون اسنوير Snower 8-Zone Panel اسنوير سنوير snower لوحة لوحات كنترول بانل panel control panel زون zone conventional',
   '{"zones":8}', 'limited', 34),
  ('snower-smoke-detector', 'smoke-detectors', 'snower', 'conventional', 'حساس دخان اسنوير', 'Snower Smoke Detector',
   'كاشف إنذار تقليدي قياسي. يعمل بجهد 24V DC، استشعار سريع للدخان.',
   'Standard conventional alarm detector. Operates at 24V DC with fast smoke sensing.',
   'حساس دخان اسنوير Snower Smoke Detector اسنوير سنوير snower حساس دخان كاشف smoke detector تقليدي conventional',
   '{}', 'in_stock', 35),
  ('snower-heat-detector', 'heat-detectors', 'snower', 'conventional', 'حساس حرارة اسنوير', 'Snower Heat Detector',
   'كاشف إنذار تقليدي قياسي. يعمل بجهد 24V DC، استشعار سريع للحرارة.',
   'Standard conventional alarm detector. Operates at 24V DC with fast heat sensing.',
   'حساس حرارة اسنوير Snower Heat Detector اسنوير سنوير snower حساس حرارة كاشف heat detector تقليدي conventional',
   '{}', 'in_stock', 36),
  ('snower-mcp', 'manual-call-points', 'snower', 'conventional', 'كاسر اسنوير', 'Snower Manual Call Point',
   'وحدة تفعيل يدوي للإنذار. متوافقة مع الأنظمة التقليدية ومصنوعة من مواد خفيفة وعالية التحمل.',
   'Manual alarm activation unit. Compatible with conventional systems, made of lightweight, highly durable materials.',
   'كاسر اسنوير Snower Manual Call Point اسنوير سنوير snower كاسر كسر زجاج manual call point break glass تقليدي conventional',
   '{}', 'in_stock', 37),
  ('snower-siren', 'sirens', 'snower', null, 'سرينة اسنوير', 'Snower Siren',
   'وحدة تنبيه صوتية. متوافقة مع الأنظمة التقليدية ومصنوعة من مواد خفيفة وعالية التحمل.',
   'Audible alert unit. Compatible with conventional systems, made of lightweight, highly durable materials.',
   'سرينة اسنوير Snower Siren اسنوير سنوير snower سرينة سيرينة صفارة siren',
   '{}', 'in_stock', 38),
  ('snower-bell', 'bells', 'snower', null, 'جرس اسنوير', 'Snower Bell',
   'وحدة تنبيه صوتية (جرس). متوافقة مع الأنظمة التقليدية ومصنوعة من مواد خفيفة وعالية التحمل.',
   'Audible alert unit (bell). Compatible with conventional systems, made of lightweight, highly durable materials.',
   'جرس اسنوير Snower Bell اسنوير سنوير snower جرس اجراس bell',
   '{}', 'in_stock', 39),
  ('generic-chinese-mcp', 'manual-call-points', 'generic-chinese', null, 'كاسر زجاج يدوي (صيني المنشأ)', 'Chinese-origin Manual Call Point',
   'جهاز تفعيل يدوي اقتصادي. نقطة استدعاء يدوية لتفعيل الإنذار.',
   'Economy manual activation device. Manual call point for triggering the alarm.',
   'كاسر صيني Chinese-origin Manual Call Point صيني china chinese كاسر كسر زجاج manual call point break glass',
   '{}', 'in_stock', 40),
  ('generic-chinese-siren', 'sirens', 'generic-chinese', null, 'سرينة صيني', 'Chinese-origin Siren',
   'سرينة تنبيه اقتصادية. تعمل على جهد 24V DC.',
   'Economy alert siren. Operates at 24V DC.',
   'سرينة صيني Chinese-origin Siren صيني china chinese سرينة سيرينة صفارة siren',
   '{"voltage":24}', 'in_stock', 41),
  ('generic-chinese-bell-24v', 'bells', 'generic-chinese', null, 'جرس صيني 24 فولت', 'Chinese-origin Bell 24V',
   'جرس تنبيه صوتي ميكانيكي. تعمل بتغذية مستمرة 24V DC من النظام.',
   'Mechanical audible alert bell. Powered by a continuous 24V DC supply from the system.',
   'جرس صيني 24 فولت Chinese-origin Bell 24V صيني china chinese جرس اجراس bell',
   '{"voltage":24}', 'in_stock', 42),
  ('generic-chinese-bell-220v', 'bells', 'generic-chinese', null, 'جرس صيني 220 فولت', 'Chinese-origin Bell 220V',
   'جرس تنبيه صوتي ميكانيكي. تعمل بجهد 220V AC للتوصيل المباشر.',
   'Mechanical audible alert bell. Operates at 220V AC for direct connection.',
   'جرس صيني 220 فولت Chinese-origin Bell 220V صيني china chinese جرس اجراس bell',
   '{"voltage":220}', 'in_stock', 43),
  ('generic-chinese-4-zone-panel', 'control-panels', 'generic-chinese', null, 'لوحة 4 زون صيني', 'Chinese-origin 4-Zone Panel',
   'لوحة إنذار حريق تقليدية اقتصادية. تغطي 4 مناطق إنذار وتدعم التشغيل بالبطاريات.',
   'Economy conventional fire alarm panel. Covers 4 alarm zones and supports battery operation.',
   'لوحة 4 زون صيني Chinese-origin 4-Zone Panel صيني china chinese لوحة لوحات كنترول بانل panel control panel زون zone conventional',
   '{"zones":4}', 'in_stock', 44),
  ('generic-chinese-beam-detector', 'beam-detectors', 'generic-chinese', null, 'بيم صيني', 'Chinese-origin Beam Detector',
   'كاشف دخان شعاعي اقتصادي. مناسب للمساحات المفتوحة والصالات المغطاة.',
   'Economy beam smoke detector. Suitable for open spaces and covered halls.',
   'بيم صيني Chinese-origin Beam Detector صيني china chinese بيم beam detector حساس شعاعي',
   '{}', 'in_stock', 45),
  ('generic-chinese-abort-switch', 'abort-switches', 'generic-chinese', null, 'ابورت صيني', 'Chinese-origin Abort Switch',
   'زر إجهاض وتأخير (Abort) لإيقاف تفريغ الغاز مؤقتًا. يمنع التفريغ الخاطئ لغاز الإطفاء عند وقوع إنذار غير مؤكد.',
   'Abort and delay button that temporarily halts gas discharge. Prevents accidental discharge of extinguishing gas during an unconfirmed alarm.',
   'ابورت صيني Chinese-origin Abort Switch صيني china chinese ابورت ابورة abort switch',
   '{}', 'in_stock', 46),
  ('fire-search-extinguisher-6kg', 'extinguishers', 'generic-chinese', null, 'طفاية فاير سيرش 6 كيلو صيني', 'Fire Search Extinguisher 6kg (Chinese origin)',
   'نظام إطفاء تلقائي مدمج يعمل عبر الأنابيب الحرارية. يُركب داخل الكبائن ولوحات الكهرباء المغلقة ويفرّغ تلقائيًا عند الارتفاع الحراري.',
   'Built-in automatic extinguishing system operating through heat-sensitive tubes. Installed inside cabins and enclosed electrical panels and discharges automatically on a heat rise.',
   'طفاية فاير سيرش 6 كيلو صيني Fire Search Extinguisher 6kg (Chinese) صيني china chinese طفاية طفايه fire extinguisher',
   '{"weight_kg":6}', 'on_request', 47),
  ('fire-search-extinguisher-2kg', 'extinguishers', 'generic-chinese', null, 'طفاية فاير سيرش 2 كيلو صيني', 'Fire Search Extinguisher 2kg (Chinese origin)',
   'نظام إطفاء تلقائي مدمج يعمل عبر الأنابيب الحرارية. يُركب داخل الكبائن ولوحات الكهرباء المغلقة ويفرّغ تلقائيًا عند الارتفاع الحراري.',
   'Built-in automatic extinguishing system operating through heat-sensitive tubes. Installed inside cabins and enclosed electrical panels and discharges automatically on a heat rise.',
   'طفاية فاير سيرش 2 كيلو صيني Fire Search Extinguisher 2kg (Chinese) صيني china chinese طفاية طفايه fire extinguisher',
   '{"weight_kg":2}', 'on_request', 48),
  ('aluminum-cables', 'cables', null, null, 'كابلات الومنيوم', 'Aluminum Cables',
   'كابلات بأطوال متعددة (500 / 410 / 85 / 60 متر) لتغذية اللوحات والمعدات. مناسبة لخطوط التغذية والتوصيل المباشر بين المكونات.',
   'Cables in multiple lengths (500 / 410 / 85 / 60 m) for powering panels and equipment. Suitable for supply lines and direct connection between components.',
   'كابلات الومنيوم Aluminum Cables كابل كابلات cable',
   '{"material":"aluminum"}', 'on_request', 49),
  ('copper-cables', 'cables', null, null, 'كابلات نحاس', 'Copper Cables',
   'كابلات لتوصيل شبكات وكواشف الإنذار. نحاس نقي بمقاومة منخفضة لضمان استقرار إشارات البيانات والإنذار.',
   'Cables for connecting alarm networks and detectors. Pure copper with low resistance to ensure stable data and alarm signals.',
   'كابلات نحاس Copper Cables كابل كابلات cable',
   '{"material":"copper"}', 'on_request', 50),
  ('battery-2-3ah', 'batteries', null, null, 'بطارية 2.3 امبير', '2.3 Ah Battery',
   'بطارية جافة 12V سعة 2.3 أمبير لتغذية اللوحات عند انقطاع الكهرباء. تُركب بشكل زوجي لتأمين جهد 24V DC للوحات الإنذار.',
   '12V dry battery, 2.3 Ah, powering panels during power outages. Installed as a pair to provide 24V DC for alarm panels.',
   'بطارية 2.3 امبير 2.3 Ah Battery بطارية بطاريه امبير battery',
   '{"capacity_ah":2.3,"voltage":12}', 'on_request', 51),
  ('battery-7ah', 'batteries', null, null, 'بطارية 7 امبير', '7 Ah Battery',
   'بطارية جافة 12V سعة 7 أمبير لتغذية اللوحات عند انقطاع الكهرباء. تُركب بشكل زوجي لتأمين جهد 24V DC للوحات الإنذار.',
   '12V dry battery, 7 Ah, powering panels during power outages. Installed as a pair to provide 24V DC for alarm panels.',
   'بطارية 7 امبير 7 Ah Battery بطارية بطاريه امبير battery',
   '{"capacity_ah":7,"voltage":12}', 'in_stock', 52),
  ('tanda-beam-detector', 'beam-detectors', 'tanda', null, 'بيم تاندا', 'Tanda Beam Detector',
   'كاشف دخان شعاعي. تغطية مسافات واسعة في الصالات والمخازن.',
   'Beam smoke detector. Covers long distances in halls and warehouses.',
   'بيم تاندا Tanda Beam Detector تاندا tanda بيم beam detector حساس شعاعي',
   '{}', 'on_request', 53),
  ('ats-conventional-heat-detector', 'heat-detectors', 'ats', 'conventional', 'حساس حرارة تقليدي ats', 'ATS Conventional Heat Detector',
   'كاشف حراري تقليدي. نظام استشعار تقليدي قياسي.',
   'Conventional heat detector. Standard conventional sensing system.',
   'حساس حرارة تقليدي ats ATS Conventional Heat Detector ats اي تي اس حساس حرارة كاشف heat detector تقليدي conventional',
   '{}', 'in_stock', 54),
  ('ats-detector-base', 'detector-bases', 'ats', null, 'قاعدة ats', 'ATS Detector Base',
   'القاعدة المخصصة لكاشف الحرارة ATS. قاعدة تثبيت للكاشف مع توصيل الدائرة.',
   'Dedicated base for the ATS heat detector. Mounting base for the detector with circuit terminals.',
   'قاعدة ats ATS Detector Base ats اي تي اس قاعدة base detector base',
   '{}', 'in_stock', 55),
  ('apollo-extinguishing-panel', 'control-panels', 'apollo', null, 'لوحة اطفاء ابولو', 'Apollo Extinguishing Panel',
   'لوحة إنذار وإطفاء تقليدية بمواصفات جودة بريطانية. اعتمادية عالية، مطابقة لمواصفات EN54 وLPCB، ودوائر مراقبة محمية.',
   'Conventional alarm and extinguishing panel built to British quality standards. High reliability, compliant with EN54 and LPCB standards, with protected supervised circuits.',
   'لوحة اطفاء ابولو Apollo Extinguishing Panel ابولو apollo لوحة لوحات كنترول بانل panel control panel',
   '{}', 'in_stock', 56),
  ('apollo-2-zone-panel', 'control-panels', 'apollo', null, 'لوحة 2 زون ابولو', 'Apollo 2-Zone Panel',
   'لوحة إنذار حريق تقليدية 2 زون بمواصفات جودة بريطانية. اعتمادية عالية، مطابقة لمواصفات EN54 وLPCB، ودوائر مراقبة محمية.',
   '2-zone conventional fire alarm panel built to British quality standards. High reliability, compliant with EN54 and LPCB standards, with protected supervised circuits.',
   'لوحة 2 زون ابولو Apollo 2-Zone Panel ابولو apollo لوحة لوحات كنترول بانل panel control panel زون zone conventional',
   '{"zones":2}', 'in_stock', 57),
  ('apollo-8-zone-panel', 'control-panels', 'apollo', null, 'لوحة 8 زون ابولو', 'Apollo 8-Zone Panel',
   'لوحة إنذار حريق تقليدية 8 زون بمواصفات جودة بريطانية. اعتمادية عالية، مطابقة لمواصفات EN54 وLPCB، ودوائر مراقبة محمية.',
   '8-zone conventional fire alarm panel built to British quality standards. High reliability, compliant with EN54 and LPCB standards, with protected supervised circuits.',
   'لوحة 8 زون ابولو Apollo 8-Zone Panel ابولو apollo لوحة لوحات كنترول بانل panel control panel زون zone conventional',
   '{"zones":8}', 'limited', 58),
  ('apollo-1-loop-panel', 'control-panels', 'apollo', null, 'لوحة 1لوب ابولو', 'Apollo 1-Loop Panel',
   'لوحة تحكم معنونة 1 لوب للنظم المتوسطة والكبيرة. دعم بروتوكولات Apollo المعنونة (XP95 / Discovery)، وسعة 126 نقطة لكل حلقة.',
   'Addressable 1-loop control panel for medium and large systems. Supports Apollo addressable protocols (XP95 / Discovery), with a capacity of 126 points per loop.',
   'لوحة 1لوب ابولو Apollo 1-Loop Panel ابولو apollo لوحة لوحات كنترول بانل panel control panel لوب loop addressable معنونة',
   '{"loops":1}', 'limited', 59),
  ('apollo-2-loop-panel', 'control-panels', 'apollo', null, 'لوحة 2 لوب ابولو', 'Apollo 2-Loop Panel',
   'لوحة تحكم معنونة 2 لوب للنظم المتوسطة والكبيرة. دعم بروتوكولات Apollo المعنونة (XP95 / Discovery)، وسعة 126 نقطة لكل حلقة.',
   'Addressable 2-loop control panel for medium and large systems. Supports Apollo addressable protocols (XP95 / Discovery), with a capacity of 126 points per loop.',
   'لوحة 2 لوب ابولو Apollo 2-Loop Panel ابولو apollo لوحة لوحات كنترول بانل panel control panel لوب loop addressable معنونة',
   '{"loops":2}', 'limited', 60),
  ('apollo-conventional-mcp', 'manual-call-points', 'apollo', 'conventional', 'كاسر ابولو تقليدي', 'Apollo Conventional Manual Call Point',
   'كاسر يدوي من مكونات الإنذار التقليدية عالية الدقة والأمان. استجابة فائقة، خامات مقاومة للحرارة وخالية من الهالوجين، مطابقة للمواصفات الأوروبية.',
   'Manual call point - a high-precision, high-safety conventional alarm component. Very fast response, heat-resistant halogen-free materials, compliant with European standards.',
   'كاسر ابولو تقليدي Apollo Conventional Manual Call Point ابولو apollo كاسر كسر زجاج manual call point break glass تقليدي conventional',
   '{}', 'in_stock', 61),
  ('apollo-conventional-smoke-detector', 'smoke-detectors', 'apollo', 'conventional', 'حساس دخان ابولو تقليدي', 'Apollo Conventional Smoke Detector',
   'حساس دخان من مكونات الإنذار التقليدية عالية الدقة والأمان. استجابة فائقة، خامات مقاومة للحرارة وخالية من الهالوجين، مطابقة للمواصفات الأوروبية.',
   'Smoke detector - a high-precision, high-safety conventional alarm component. Very fast response, heat-resistant halogen-free materials, compliant with European standards.',
   'حساس دخان ابولو تقليدي Apollo Conventional Smoke Detector ابولو apollo حساس دخان كاشف smoke detector تقليدي conventional',
   '{}', 'in_stock', 62),
  ('apollo-conventional-heat-detector', 'heat-detectors', 'apollo', 'conventional', 'حساس حرارة ابولو تقليدي', 'Apollo Conventional Heat Detector',
   'حساس حرارة من مكونات الإنذار التقليدية عالية الدقة والأمان. استجابة فائقة، خامات مقاومة للحرارة وخالية من الهالوجين، مطابقة للمواصفات الأوروبية.',
   'Heat detector - a high-precision, high-safety conventional alarm component. Very fast response, heat-resistant halogen-free materials, compliant with European standards.',
   'حساس حرارة ابولو تقليدي Apollo Conventional Heat Detector ابولو apollo حساس حرارة كاشف heat detector تقليدي conventional',
   '{}', 'limited', 63),
  ('apollo-detector-base', 'detector-bases', 'apollo', null, 'قاعدة ابولو', 'Apollo Detector Base',
   'قاعدة حساسات من مكونات الإنذار التقليدية عالية الدقة والأمان. استجابة فائقة، خامات مقاومة للحرارة وخالية من الهالوجين، مطابقة للمواصفات الأوروبية.',
   'Detector base - a high-precision, high-safety conventional alarm component. Very fast response, heat-resistant halogen-free materials, compliant with European standards.',
   'قاعدة ابولو Apollo Detector Base ابولو apollo قاعدة base detector base',
   '{}', 'in_stock', 64),
  ('hlt-conventional-smoke-detector', 'smoke-detectors', 'hlt', 'conventional', 'حساس دخان تقليدي hlt', 'HLT Conventional Smoke Detector',
   'كاشف دخان ضوئي اقتصادي وعملي. استجابة سريعة ومتوافق مع اللوحات التقليدية.',
   'Economy and practical photoelectric smoke detector. Fast response and compatible with conventional panels.',
   'حساس دخان تقليدي hlt HLT Conventional Smoke Detector hlt اتش ال تي حساس دخان كاشف smoke detector تقليدي conventional',
   '{}', 'in_stock', 65)
)
insert into public.products (slug, category_id, brand_id, system_type, name_ar, name_en,
                             description_ar, description_en, search_keywords,
                             specs, availability, sort_order, is_published)
select
  s.slug, c.id, b.id, s.system, s.name_ar, s.name_en,
  s.description_ar, s.description_en, s.search_keywords,
  s.specs, s.availability, s.sort_order, true
from s
join public.categories c on c.slug = s.category
left join public.brands b on b.slug = s.brand
on conflict (slug) do update set
  description_ar  = coalesce(nullif(public.products.description_ar, ''),  excluded.description_ar),
  description_en  = coalesce(nullif(public.products.description_en, ''),  excluded.description_en),
  search_keywords = coalesce(nullif(public.products.search_keywords, ''), excluded.search_keywords);

-- ── Initial featured selection (8) — admin can change per product ────────
update public.products set is_featured = true
where slug in (
  'hst-economy-4-zone-panel', 'hst-silver-8-zone-panel',
  'hst-conventional-smoke-detector', 'hst-conventional-heat-detector',
  'hst-addressable-smoke-detector', 'hst-mcp',
  'hst-siren', 'battery-7ah'
);

-- ── Site content ─────────────────────────────────────────────────────────
-- Company details (name, email, address) are real. Hours, about texts and "why us"
-- copy are still placeholders until edited in the admin.
insert into public.site_settings (key, value_ar, value_en)
select v.key, v.value_ar, v.value_en
from (values
  ('company_name', 'ريتش', 'Reach'),
  ('tagline', 'توريد أنظمة إنذار الحريق والكواشف والملحقات في مصر.',
             'Supply of fire alarm systems, detectors and accessories in Egypt.'),
  ('hours', 'السبت إلى الخميس · من 9 صباحًا إلى 6 مساءً',
            'Saturday to Thursday · 9:00 AM to 6:00 PM'),
  ('address', 'مدينة العاشر من رمضان – طريق الأردنية (7PXV+XQM)',
              '10th of Ramadan City – Al-Ordoneya Road (7PXV+XQM)'),
  ('email', 'reach.ad.tech@gmail.com', 'reach.ad.tech@gmail.com'),
  ('map_url', 'https://www.google.com/maps/search/?api=1&query=7PXV%2BXQM',
              'https://www.google.com/maps/search/?api=1&query=7PXV%2BXQM'),
  ('hero_eyebrow', 'أنظمة إنذار الحريق', 'Fire alarm systems'),
  ('hero_title', 'توريد مشروعك يبدأ *بحزمة متكاملة* لأنظمة إنذار الحريق',
                 'Build your project scope with a *complete supply package* for fire alarms'),
  ('hero_lead', 'توريد لوحات تحكم وكواشف وصفارات وملحقات — تقليدية ومعنونة — مع دعم فني قبل وبعد التوريد.',
                'Supply of conventional and addressable control panels, detectors, sounders and accessories, with technical support before and after supply.'),
  ('about_story', null, null),
  ('about_vision', null, null),
  ('why_1_title', 'خبرة فنية', 'Technical experience'),
  ('why_1_body', 'فريق متخصص في توريد أنظمة الإنذار التقليدية والمعنونة.',
                 'A specialist team supplying conventional and addressable alarm systems.'),
  ('why_2_title', 'ضمان الموزع المعتمد', 'Authorized distributor warranty'),
  ('why_2_body', 'ضمان الموزع المعتمد للعلامات التي نمثلها، وفق شروط كل علامة.',
                 'Authorized distributor warranty for the brands we represent, subject to each brand’s terms.'),
  ('why_3_title', 'دعم فني قبل وبعد التوريد', 'Technical support before and after supply'),
  ('why_3_body', 'متابعة فنية واستشارات اختيار المعدات المناسبة لمشروعك.',
                 'Technical follow-up and advice on choosing the right equipment for your project.')
) as v(key, value_ar, value_en)
on conflict (key) do nothing;

-- Owner-provided contact numbers (E.164): sales/WhatsApp first, technical support second.
insert into public.contact_numbers (label_ar, label_en, number, is_whatsapp, sort_order)
select v.label_ar, v.label_en, v.number, v.is_whatsapp, v.sort_order
from (values
  ('مبيعات', 'Sales', '+201030006425', true, 1),
  ('دعم فني', 'Technical support', '+201042956387', false, 2)
) as v(label_ar, label_en, number, is_whatsapp, sort_order)
where not exists (select 1 from public.contact_numbers);

-- No social links are seeded: add verified profiles through the admin.